const path = require('path');
const { BASIC_UPLOADING_FOLDER_PATH } = require('../config/upload');

//Locla Services
const CodeScanner = require('../services/CodeScanner');
const ScanResult = require('../services/DTO/ScanResult')
const ZipProcessor = require('../services/ZipProcessor')


//Repositories
const DataBaseTransactionManager = require('../repositories/DataBaseTransactionManager');
const UserRepository = require('../repositories/UserRepository')
const ProjectRepository = require('../repositories/ProjectRepository');

//Enums
const CodeScannerTool = require('../enums/CodeScannerTool');

//Helpers/Utility
const AuthJwtPayload = require('../utils/AuthJwtPayload');
const GitRepoHelper = require('../utils/GitRepoHelper')
const RecordScanHelper = require('../utils/RecordScanHelper')

const AuthPlayload = require('../utils/AuthJwtPayload');

/**
 * Help an user add a project to his account with git_url
 * @param {*} req 
 * @param {*} res 
 * @returns 
 */
exports.addProjectWithURL = async (req, res) => {
    //Data validation
    const { name, repoUrl, token } = req.body;
    console.log({name, repoUrl, token})

    /** @type {AuthPlayload} authPayload */
    const authPayload = req.user;

    if(
        !repoUrl || typeof repoUrl !== 'string'
    ){
        return res.status(400).json({ 
            success: false,
            message: 'Veuillez fournir tous les champs requis : repoUrl. Il s\'agit de chaine de caractères'
        });
    }


    //Check repository existance
    console.log({repoUrl, userId: authPayload.sub, token})
    const doesRepoExixt = await GitRepoHelper.repoExists(repoUrl, authPayload.sub, token)
    if(!doesRepoExixt){
        return res.status(400).json({
            success: false, 
            message: 'Le dépôt GitHub spécifié n\'existe pas ou est inaccessible'
        })
    }
    
    try {
        //Save the project in the database
        const cleanName = name ?? repoUrl?.split('/').pop()?.replace(/\.git$/, '');
        const {alreadyExists, userProject} = await ProjectRepository.addProject(
            authPayload.sub, {
                name: cleanName, url: repoUrl
            }
        )

        if(alreadyExists)
        {
            return res.json({
                success: true,
                message: "Projet déjà sauvegarder en bdd",
                data: userProject
            })
        }

        return res.status(200).json({ 
            success: true,
            message: 'Projet ajouté avec succès',
            data: userProject
        })
    }
    catch (error) {
        //Log the error & return a messg to the client
        console.log('Erreur lors de l\'ajout du projet :', error);
        return res.status(500).json({ 
            success: false,
            message: 'Erreur lors de l\'ajout du projet'
        });
    }
}


/**
 * Allow an user to add a project with a zip file
 * @param {*} req 
 * @param {*} res 
 * @returns 
 */
exports.addProjectWithZip = async (req, res) => {   
    try{
        //Data validation
        /** @var {AuthPlayload} authPayload */
        const authPayload = req.user;
        const file = req.file;
        
        // console.log("Fichier Zip uploaded: ", file)
        if (!file || !file.originalname.endsWith('.zip'))
        {
            console.log('Missing or invalid Zip File')
            return res.status(400).json({ success: false, message: 'Zip File manquant'})
        }

        const zipFileName = Date.now() + '_' + file.originalname.replace(/\s+/g, '_');                          //the name of the file in a unique format to avoid any conflicts
        
        const userProjectPath  = `${authPayload.sub}/projects/${zipFileName}`
        const destPath = path.join(BASIC_UPLOADING_FOLDER_PATH, userProjectPath );  //final folder destination where the file will be unzipped

        //Save the project in the database & decompress the zip file in the same time, 
        // if any error occurs we will rollback the transaction and delete any decompressed files if needed
        await DataBaseTransactionManager.executeTransaction(async({commit, rollback})=>{
            try{
                const { id: projectId, alreadyExists, userProject } = await ProjectRepository.addProject(authPayload.sub, {
                    name: file.originalname,        //The name sent by the client
                    original_name: zipFileName,     //The unique name generated by the server
                    url: userProjectPath ,          //A custom string indicating the place  where the zip file is saved in the src/upload folder (that is to be created if not) 
                    is_uploaded: true
                })

                if(alreadyExists)
                {
                    console.log("Repo elready exists in bdd, so we return a positive response")
                    return res.json({
                        message: "Repo déjà exitant ou upload!!",
                        success: true,
                        data: userProject
                    })
                }

                console.log("-----Save zip line----")
                await ZipProcessor.saveZipFolder(file.buffer, destPath)
                await commit();

                return res.status(200).json({ 
                    success: true,
                    message: 'Projet ajouté avec succès',
                    data: userProject
                })
            }
            catch(error)
            {
                console.log('Error while processing the zip file : ', error)
                await rollback();
                return res.status(500).json({ 
                    success: false,
                    message: 'Une erreur est survenue lors du traitement du fichier ZIP'
                })
            }
        })
    }
    catch (error) {
        console.log('Something went wrong !! ', error)
        return res.status(500).json({ 
            success: false,
            message: 'Une erreur est survenue lors de l\'ajout du projet'
        })
    }
}



/**
 * Allow an user to scan a project with the selected scanning tools
 * @param {*} req 
 * @param {*} res 
 * @returns 
 */
exports.scanRepo = async (req, res) => {
    //Data validation
    const { projectId, repoUrl, scanTools } = req.body;

    if (!repoUrl) {
        return res.status(400).json({ success: false, message: 'repoUrl manquant' });
    }

    if(!Array.isArray(scanTools) || scanTools.length === 0){
        return res.status(400).json({ 
            success: false,
            message: 'scanTools ne doit pas être vide'
        });
    }

    // -- Check that only valid scanning tools are provided
    if(!scanTools.every(tool => CodeScannerTool.isValidTool(tool))){
        return res.status(400).json({ 
            success: false,
            message: 'scanTools contient des outils de scan invalides. Les outils valides sont : semgrep, eslint, npmAudit'
        });
    }

    /** @var {AuthJwtPayload} user */
    const user = req.user;

    // -- Project existence validation
    try{
        await ProjectRepository.assessProjectOwnership(user.sub, projectId)
    }
    catch(error){
        console.log('Error while validating project ownership : ', error)
        return res.status(403).json({
            success: false,
            message: 'Vous n\'avez pas la permission d\'accéder à ce projet'
        })
    };

    try {

        //Processed with the code scanner service
        /** @type {ScanResult} */
        const scanResult = await CodeScanner.performScan({
            repoUrl,
            scanTools
        });
        
        let results;
        //Save database analisys resutlt
        DataBaseTransactionManager.executeTransaction(async({ commit, rollback })=>{
            try{
                results = await RecordScanHelper.execute(scanResult)
                await commit()
            }
            catch(error)
            {
                console.log("Something went wrong!!, error: ", error?.message)
                await rollback()
                return res.json({
                    success: false,
                    message: 'Scan échoué'
                }).status(400)
            }
        })
        //Retunn the scan results to the client
        return res.status(200).json({ success: true, results });
    }
    catch (error) {
        console.error('Erreur lors du scan:', error);
        return res.status(500).json({ success: false, message: "Action échoué" });
    }
};





exports.scanZip = async (req, res) => {

    //Data validation
    const { projectId, scanTools } = req.body;

    console.log({projectId, scanTools})

    if(!Array.isArray(scanTools) || scanTools.length === 0){
        return res.status(400).json({ 
            success: false,
            message: 'scannTools ne doit pas être vide'
        });
    }

    /** @var {AuthJwtPayload} user */
    const user = req.user;

    //Project existence validation
    try{
        await ProjectRepository.assessProjectOwnership(user.sub, projectId)
    }
    catch(error){
        console.log('Error while validating project ownership : ', error)
        return res.status(403).json({
            success: false,
            message: 'Vous n\'avez pas la permission d\'accéder à ce projet'
        })
    };

    // Saving
    try {
        const project = await ProjectRepository.getProjectById(projectId)
        
        //Check if the project is uploaded with a zip or added with a git url
        if(!project?.isUploaded)
            return res.status(400).json({
                success: false,
                message: 'Ce projet n\'a pas été ajouté avec un fichier ZIP'
            })

        //Processed with the code scanner service
        /** @type {ScanResult} */
        const scanResult = await CodeScanner.performZipScan({
            zip_name: project.originalName,
            userId: user.sub,
            scanTools
        });
        
        let results = {};
        //Save database analisys resutlt
        DataBaseTransactionManager.executeTransaction(async({commit , rollback })=>{
            try{
                results  = await RecordScanHelper.execute(scanResult)
                commit()
            }
            catch(error)
            {
                console.log("Something went wrong!!, error: ", error?.message)
                rollback()
                return res.json({
                    success: false,
                    message: 'Scan échoué',
                    data: {}
                }).status(400)
            }
        })

        return res.status(200).json({ success: true, data: results });
    }
    catch (error) {
        console.error('Erreur lors du scan du ZIP:', error);
        return res.status(500).json({ success: false, message: 'Action echoué' });
    }
};
