// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv


const envFileConfig = {
  path: '.env'
}
require('dotenv').config(envFileConfig);

const { defineConfig } = require('prisma/config')

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
