
//entities
const Finding = require('../valueObjects/Finding');
const LineInfo = require('../valueObjects/LineInfo')

//enums
const CodeScannerTool = require('../enums/CodeScannerTool')

//Repositories
const FindingRepository = require('../repositories/FindingRepository')
const SecurityRuleRepository = require('../repositories/SecurityRuleRepository')
const AnalysisToolRepository = require('../repositories/AnalysisToolsRepository')
const AnalysisRecordRepository = require('../repositories/AnalysisRecordRepository')

//Services
const ScanResult = require("../services/DTO/ScanResult");
const MappedIssue = require('../services/DTO/MappedIssue')

//Utility
const ScoreAnalizer = require('./ScoreAnalyzer');
const CodeScanner = require('../services/CodeScanner')

class RecordScanHelper
{
    /**
     * This one help integrate all the data needed for bdd
     * @param {ScanResult} scanResult - the result after scan
     */
    static async execute(projectId, scanResult)
    {
        const analysisTools = [];

        //calculate score
        const scoreBadge = ScoreAnalizer.analyze(securityPoints)
        const securityPoints = CodeScanner.calculateSecurityScorePoints(scanResult.owasp)

        //Create analysis record
        const analysisRecord = await AnalysisRecordRepository.addAnalysisRecord({ 
            project_id: projectId,
            score: scoreBadge
        });

        //Record Semgrep Finding result Into Bdd
        if(Array.isArray(scanResult.semgrepResults) && scanResult.semgrepResults.length> 0)
        {
            /** @type {{ [key: string]: MappedIssue[] }} */
            const owasp = scanResult.owasp ?? {}
            for(const [key, value]  of Object.entries(owasp)){
                for(issue of owasp){
                    await this.recordMappedIssue(issue, key, CodeScannerTool.SEMGREP)
                }
            }
            analysisTools.push(CodeScannerTool.SEMGREP)
        }
        
        //Record ESLint result into bdd
        if(Array.isArray(scanResult.eslint) && scanResult.eslint.length > 0)
        {
            const eslint = scanResult.eslint;
            for(issue of eslint){
                await this.recordMappedIssue(issue, null, CodeScannerTool.ESLINT)
                analysisTools.push(CodeScannerTool.ESLINT)
            }
            analysisTools.push(CodeScannerTool.ESLINT)
        }

        //Record Npm Audit record into bdd
        if(Array.isArray(scanResult.npmAudit) && scanResult.eslint.length > 0)
        {
            const audit = scanResult.npmAudit
            for(const issue of audit){
                await this.recordMappedIssue(audit, null, CodeScannerTool.NPM_AUDIT )
            }
            analysisTools.push(CodeScannerTool.NPM_AUDIT)
        }

        await AnalysisRecordRepository.addAnalysisTools(analysisTools)
    }



    /** 
     * @param {MappedIssue} issue - the issue generated by the scan
     * @param {string?} category_key - the owasp category key with error
     * @param {string} analysis_tool - the category key with error
     * */
    async recordMappedIssue(issue, category_key =null, analysis_tool) {
        const {
            check_id,
            file_path,
            code,
            severity ,
            message: description,
            start_index,
            end_index,
            fingerprint
        } = issue;

        const owaspVulnerabilityError = metadata?.owasp || [];
        const rule  = await SecurityRuleRepository.addRule({ check_id, description })
        const tools = await AnalysisToolRepository.getToolByName(analysis_tool)

        const finding = new Finding({
            file_path,
            severity: Finding.mapSeverity(severity, category_key),
            code,
            tool_id: tools.id,
            rule_id: rule.id,
            fingerprint ,
            owaspVulnerabilityError,
            analysis_record_id: analysisRecord.id,
            code: code.join('\n'),
            owaspVulnerabilityError
        });

        const insertedFinding = await FindingRepository.addFinding(finding)

        const lineInfo = new LineInfo({start_index, end_index});
        await FindingRepository.addLineInfoToFinding(insertedFinding.id, lineInfo)
    }

}

module.exports = RecordScanHelper